### ISSUE TITLE
Duplicated responses in ProjectsController#index and ProjectsCountsController#index

### ISSUE THREAD

**Issue by athal7** [mikesea/donors_select#17]

**Comment by mikesea** [comment]
So, this is largely due to how Spine handles and parses JSON responses from your API. We basically had to create a separate controller just handle the meta information about projects, which is dynamically rendered as you continue clicking filters on the page. Not ideal, but, luckily, Redis reads are "cheap."

**Comment by athal7** [comment]
ah very cool, i tried to play with it for a while and it was not easy, very cool how you guys set this up

**Comment by mikesea** [comment]
Thank you! Happy to walk through some of this in more detail if you'd like.

**Comment by athal7** [comment]
yea that would be awesome!
